/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Jessin' at '20-2-18 11:10' with Gradle 2.13
 *
 * @author Jessin, @date 20-2-18 11:10
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
